services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://mongodb:J4g31XXIiU2GMduY@cluster0.qcuqc4q.mongodb.net/sbd-project?retryWrites=true&w=majority&appName=Cluster0 
      - PORT=3000    
    depends_on:
      - database
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./client:/app
      - /app/node_modules

  database:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: